version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U citat-side"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local_dev_network
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - local_dev_network
    ports:
    - 8080:8080
volumes:
  db-data:
networks:
  local_dev_network: